.github: remove Python 3.5 and 3.6
GitHub removed Python 3.5 from the test matrix. It now returns:

    Error: The version '3.5' with architecture 'x64' was not found for Ubuntu 22.04.
    The list of all available versions can be found here:
    https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json

Python 3.6 is also only available on Ubuntu 20.04.

Python 2.7 is still there, and 3.12 appeared in alpha state so it is not
ready to be included.

On Windows Server 2022, Pypy-3.6 disappeared.