bin/podman-ghidra: update to Ghidra 10.2.3
- Ghidra now requires OpenJDK 17
- Ghidra Launcher now requires an additional parameter `jdk`

- The WebAssembly suport Pull Request needs a patch which is not in the
  Pull Request but in the upstream repository. Otherwise building fails:

    > Task :WebAssembly:compileJava FAILED
    /opt/ghidra/Ghidra/Processors/WebAssembly/src/main/java/wasm/WasmLoader.java:38: error: cannot find symbol
    import ghidra.program.model.data.DataTypeConflictException;
                                    ^
      symbol:   class DataTypeConflictException
      location: package ghidra.program.model.data
    /opt/ghidra/Ghidra/Processors/WebAssembly/src/main/java/wasm/analysis/WasmDWARFAnalyzer.java:30: error: method createSectionProviderFor in class DWARFSectionProviderFactory cannot be applied to given types;
    				&& DWARFSectionProviderFactory.createSectionProviderFor(program) != null) {
    				                              ^
      required: Program,TaskMonitor
      found:    Program
      reason: actual and formal argument lists differ in length
    /opt/ghidra/Ghidra/Processors/WebAssembly/src/main/java/wasm/WasmLoader.java:267: error: cannot find symbol
    		} catch (DataTypeConflictException e) {
    		         ^
      symbol:   class DataTypeConflictException
      location: class WasmLoader
    3 errors