Travis: upgrade python on MacOS instead of installing it
brew reports the following message:

    Error: python 2.7.14 is already installed
    To upgrade to 3.6.4_4, run `brew upgrade python`